FROM nginx:alpine
#WORKDIR /usr/share/nginx/htmls
COPY default.conf /etc/nginx/conf.d
COPY ./dist/client/ /usr/share/nginx/html/
#RUN npm install
#RUN npm install -g @angular/cli@8.3.20
EXPOSE 80/tcp
#CMD ["ng","serve","--host", "0.0.0.0"]
CMD ["/bin/sh", "-c", "exec nginx -g 'daemon off;';"]